NoteTaking/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include(('users.urls', 'core'), namespace="users")),
]

core/urls.py
"""Define o padrão de URL para appWebPython"""

from django.urls import path
from . import views

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    
    # Topicos :)
    path('topics/', views.topics, name='topics'),

    # Pagina com as entradas de um único tópico
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    
    # Pagina para o usuário criar um novo tópico
    path('new_topic/', views.new_topic, name='new_topic'),

    # Pagina para o usuário criar uma nova entrada
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    
    # Pagina pra editar uma entrada
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    

]

users/urls.py
"""Define URL patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    # login page
    path('login/', LoginView.as_view(), {'template_name': 'users/templates/registration/login.html'},
         name = 'login'),
    
    # log out page
    path('logout/', views.logout_view, name='logout'),
    
    # Register page
    path('register/', views.register, name='register'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model): 
    """User generated topic"""
    
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Returns model representation in string format"""
        
        return self.text
    
    
class Entry(models.Model):
    """Entry in a topic"""
    
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """Returns model representation in string format"""
        
        if len(self.text) < 50:
            return self.text
        
        else:
            return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    """Form that generates topic"""
        
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    """Form that generates entry"""
    
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}
    
    
    

core/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404 
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """Home page"""
    return render(request, 'index.html')


@login_required
def topics(request):
    """show the topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'topics.html', context)


@login_required
def topic(request, topic_id):
    """Show topic entries"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    
    
    entries = topic.entry_set.order_by('-date_added') # - sign inverts the date_added order
    context = {'topic' : topic, 'entries' :entries}
    return render(request, 'topic.html', context)


@login_required
def new_topic(request):
    """let the user create a new topic"""
    if request.method != 'POST':
        # creates blank form
        form = TopicForm()
        
    else: 
        # process data
        form = TopicForm(request.POST)
        
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('topics'))
    
    context = {'form': form}
    return render(request,'new_topic.html' ,context)


@login_required
def new_entry(request, topic_id):
    """Adds a new entry for a specific topic"""
    topic = Topic.objects.get(id=topic_id) #linha 24
    
    if request.method != 'POST':
        # creates blank form
        form = EntryForm()
    else:
        # process data
        form = EntryForm(data=request.POST)
        
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('topic', 
                                                args=[topic_id]))
            
    context = {'topic': topic, 'form': form}
    return render(request, 'new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edits existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    
    
    if request.method != 'POST':
        # inicial request, fill form with actual entry
        form = EntryForm(instance=entry)
    else:
        # process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form':form}
    return render(request, 'edit_entry.html', context)    

users/views.py
from django.shortcuts import render
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse


def logout_view(request):
    """Log out user"""
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    """Register user"""
    if request.method != 'POST':
        # Shows blank register form
        form = UserCreationForm()
        
    else:
        # process form
        form = UserCreationForm(a=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            
            # Log in user and redirect to home page 
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('index'))
    context = {'form': form}
    return render(request, '/home/balmaceda/appWebPython/users/templates/registration/register.html', context)

templates/base.html
<p>

    <a href ="{% url 'index' %}">Django notes</a> -  
    <a href="{% url 'topics' %}">topics</a> -
    {% if user.is_authenticated %}
        Hello, {{user.username}}.
        <a href="{% url 'users:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a>
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

templates/edit_entry.html
{% extends "base.html" %}


{% block content %}

<p><a href="{% url 'topic' topic.id %}">{{topic}}</a></p>

<p>Edit entry:</p>

<form action="{% url 'edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Apply changes</button>
</form>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<p>An app that allows you to take notes on topics you care about.
</p>
{% endblock content %}

templates/new_entry.html
{% extends "base.html" %}


{% block content %}

<p><a href="{% url 'topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>
<form action="{% url 'new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add entry</button>
</form>

{% endblock content %}

templates/new_topic.html
{% extends "base.html" %}

{% block content %}
<p>Add a topic:</p>
<form action="{% url 'new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topic</button>
</form>

{% endblock content %}

templates/topic.html
{% extends "base.html" %}

{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<p>
    <a href="{% url 'new_entry' topic.id %}">add new entry</a>
</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p> 
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'edit_entry' entry.id %}">edit entry</a>
        </p>
    </li>
    {% empty %}
    <li>
        There are no entries for this topic yet.
    </li>
    {% endfor %}
</ul>


{% endblock content %}

templates/topics.html
{% extends "base.html" %}

{% block content %}

<p>Topics:</p>

    <ul>
        {% for topic in topics %}
            <li><a href ="{% url 'topic' topic.id %}">{{topic}}</a></li>

        {% empty %}
            <li>No topics added</li>
        {% endfor %}
    </ul>

<a href="{% url 'new_topic' %}">Create new topic</a>

{% endblock content %}